// suppress inspection "JSUnusedLocalSymbols" for whole file
= KAP Tutorial
:experimental:
:doctype: book

:toc:

= Introduction

The following document is recommended for people with previous programming experience, but with no prior experience with APL or any of its cousins, such as https://www.jsoftware.com/[J], https://kx.com/[K], https://code.kx.com/q/[Q], https://mlochbaum.github.io/BQN/[BQN], etc.

== What KAP is and isn't

=== About APL

At its core, KAP is a programming language based on APL.

APL is a programming language invented by Ken Iverson in 1966 and is particularly famous for its use of non-ASCII symbols.
There exists many implementations of APL today, with the most commonly used one being https://www.dyalog.com/[Dyalog].
Dyalog is a commercial product which is free for non-commercial use.

At the risk of scaring away a beginner, here is a classic example of APL code (which also happens to be valid KAP code):

[source,kap]
----
{⊃1 ⍵ ∨.∧ 3 4 = +/ +⌿ ¯1 0 1 ∘.⊖ ¯1 0 1 ⌽¨ ⊂⍵}
----

The above example can also be found in the Wikipedia page for https://en.wikipedia.org/wiki/APL_(programming_language)[APL].

=== How KAP is different from APL

APL requires the programmer to take a very different approach to programming compared to most other programming languages.
In particular, it strongly de-emphasises the use of loops.
Traditional APL doesn't even have a looping constructs or `if` statements, with the only way to do flow control is to use goto.
Dyalog has looping constructs, but they are still cumbersome to use.

APL has often been been referred to as a "`functional`" programming language.
This is partially true, but it does lack first-class functions.
First-class functions refers to the ability to work with functions as if they were values themselves.
For example, you could create an array of functions.
Some APL derivatives such as BQN supports this concept, and Dyalog can also do it, albeit in a very roundabout way.

KAP grew out of a desire to see if it was possible to nicely integrate these programming constructs together with APL.
The question as to whether that goal has been achieved is left to the reader to determine.

Another difference that makes KAP almost unique among APL dialects is that it is centred around lazy evaluation.
It's almost unique, as APL/3000 had a similar feature all the way back in the 70's.

=== What KAP can be used for

If the reader is asking themselves if they are supposed to build the software supporting their new startup in KAP, then the answer is almost certainly no (although if they do, the author would very much like to hear about it).

Currently, the language can be seen as an alternative to Excel when working with data in array form.
Excel is great for visualising data, but performing calculations with it quickly becomes difficult as the code tends to be hidden in cells in the document.
For a programmer, this artefact of Excel is probably the most frustrating, since the code is arguably more important than the data itself.

The best way to get started is to start using KAP as a calculator by running the GUI frontend and simply typing expressions to compute things.
When users of other programming languages may take to an IDE and start writing tens or even hundreds of lines of code to perform certain calculations, KAP can do the same in sometimes just a single line of code.
It is therefore often not necessary to actually open an editor to write a program, and the user can instead simply perform their calculation directly in the tool itself.

= Using the KAP software disctribution

== Running KAP

=== Download

Currently, KAP is only available in source form and can be downloaded from https://github.com/lokedhs/array[Github].
The source code can be downloaded using the following command:

----
git clone https://github.com/lokedhs/array
----

=== Running the UI

There are different ways to run KAP, but the easiest way to get started is to use the built-in UI.
The client can be started using the following command:

----
./gradlew gui:run
----

This is the recommended way to run KAP at the moment, as it implements all language features as well as provides an easy way to enter the all the symbols used by the language.

=== Trying KAP online

KAP can be compiled to Javascript, and a simple web-based demo is available on https://kapdemo.dhsdevelopments.com/

Note that currently this website is very limited, and the user experience is not great.
In particular, it does not provide a simple way to enter the special symbols.

== Inputting APL symbols

The use of non-ASCII symbols is something that many beginners find complicated.
It is possible to configure a separate input keymap in most operating systems that support APL symbols.
However, the easiest way for a beginner to start using KAP is to use the graphical UI.
It provides a REPL as well as a text editor that provides easy access to APL symbols using two different mechanisms:

- Press kbd:[Alt] or kbd:[Meta] together with other keys. +
For example, to generate `⍴` type kbd:[Meta+r].
- Press kbd:[\`] followed by other keys. +
Type kbd:[`] followed by kbd:[Space] to generate a ```.

= First steps

== KAP basics

=== Printing text

The first thing anyone learning a new language wants to know is how to print a message to the screen.
In KAP, printing is done using `io:print` or `io:println`.
The difference between the two is that the latter adds a newline after the output.

The following code prints a string to the screen:

[source,kap]
----
io:println "Example of printing a string"
----

The name of the function is `println`, which resides in the `io` namespace.
It is possible to `import` a namespace so that one does not have to specify the namespace every time the function is used.
This is not done in this tutorial in order to make it very clear which namespace a given symbol belongs to.
Many common functions belong to the `kap` namespace which is imported by default.
Those symbols are given without the namespace.

When using the REPL to enter KAP expressions, the return value of the expression is always printed to the screen.
This is the reason why when typing the above example into the REPL, the string will be printed twice.
The first is the result of the call to `io:println` and the second is the return value of the expression. `io:println` always returns the value it printed, which results in the double output.

=== Comments

Comments in KAP are indicated using the symbol `⍝` and extends to the end of the line.

[source,kap]
----
⍝ This entire line is a comment
io:println "This will be printed"    ⍝ This is another comment
----

=== Mathematical functions

Just like any other programming languages, KAP provides functions to perform mathematical computations, the main ones are:

- `+` -- addition
- `-` -- subtraction
- `×` -- multiplication
- `÷` -- division
- `*` -- exponentiation
- `|` -- modulo

In KAP, just like in most APL implementations, evaluation happens from right-to-left.
This is probably the biggest difference compared to other languages.
This means that the following:

[source,kap]
----
3×4+5
----

evaluates to `27`.
In other words, it's interpreted as `3×(4+5)`.
This may seem somewhat strange, but the decision to interpret the code like this provides two distinct benefits: First and foremost, it removes any ambiguity as to the order in which computation will be performed.
Secondly, it reduces the number of parentheses that are needed when writing complex code.

=== Variables

Variables in KAP can be global, or they can have local bindings.
The difference between the two types of bindings will be obvious later in the tutorial, but for now this distinction can be ignored.

Variables have names starting with an alphabetic character or underscore, followed by zero or more alphabetical characters, digits or underscore.
A variable is assigned using `←` like this:

[source,kap]
----
foo ← 123        ⍝ Assigns the value 123 to the variable foo
bar ← 1+2+3      ⍝ Assigns the value 6 to the variable bar
xyz ← foo + bar  ⍝ Assigns the value 129 to the variable xyz
----

=== Statement separators

Individual statements are separated either by a newline or the symbol `⋄`.
Thus, the following:

[source,kap]
----
io:println a
io:println b
----

is equivalent to:

[source,kap]
----
io:println a ⋄ io:println b
----

=== Monadic and dyadic function invocation

Two terms that any beginner learning APL will quickly come across are the terms _monadic_ and _dyadic_.
These terms refer to the two different ways in which a function can be called:

- *Monadic* function invocation takes its argument to the right of the name. +
Example, assuming `FN` is the name of the function: `FN arg0`.
- *Dyadic* function invocation takes two arguments on each side of the function name. +
Example: `arg0 FN arg1`.

The call to `io:println` above is monadic, in that the function argument is to the right:

[source,kap]
----
io:println rightArg   ⍝ The value rightArg is to the right of the function name
----

An example of a dyadic invocation that we've already seen is the invocation of the function `+`:

[source,kap]
----
10 + 11               ⍝ The function + is called with two arguments: 10 and 11
----

It is important to note that there is nothing special about `+`.
It's a regular function just like `io:println`.
It just happens to consist of a single character instead of a word.
KAP allows the programmer to define their own functions with a single character name and the details on this will be explained later in this document.

Functions can support monadic, dyadic or both kinds of invocations.
An example of a function that allows both monadic and dyadic invocation is `-`:

[source,kap]
----
foo - 3               ⍝ Compute the result of 3 subtracted from foo
-foo                  ⍝ Negate the value of foo (if foo was 10, then the result is -10)
----

The rule for deciding whether a function invocation is monadic or dyadic is that if there is anything to the left that is a valid argument, then it's a dyadic invocation, otherwise it's monadic.
An example will help clear this up:

[source,kap]
----
10×-2                 ⍝ Result is -20
----

Looking from the right, the rightmost `-` does not have a value to the left (to the left of the `-` is a `×` symbol), and it must therefore be a monadic invocation resulting in the value `-2`.
The call to `×` is dyadic since it has a `10` to the left, so the result is the product of `10` and `-2` which is `-20`.

== Working with arrays

KAP programming is about arrays.
While the language has other container types, the array is the main way that data is organised.
Arrays are particularly important in KAP because a lot of functions are designed to work on sets of data using a single operation.
The reason array languages can get away with having poor support for flow control is that in many cases they are not needed, since one does not usually have to iterate over multiple values, and instead perform a single operation that acts on arrays of data in one go.

While KAP has stronger flow control constructs than most other array languages, the language's strength is still the focus on arrays, which is why this topic is explained even before discussing how flow control works.

=== Constructing arrays

==== Literal arrays

In many languages, arrays have only a single dimension.
Taking Javascript as an example, an array is a collection of objects which is given inside square brackets:

[source,javascript]
----
// Foo is a list of 4 values
var foo = [1, 2, "string", [4, 5]];
----

In the example above, the array consists of 4 values.
The first two are numbers, the third is a string and the fourth is another array that contains two more numbers.

In KAP, the same declaration would look like this:

[source,kap]
----
value ← 1 2 "string" (4 5)
----

As can be seen from the comparison above, KAP parses everything as arrays by default.
If more than one value is given separated by spaces, the individual values will be concatenated together and interpreted as a 1-dimensional array.

==== Iota function

It is very common to need an array consisting of numbers in ascending order.
For example, a 5-element array containing the values `0 1 2 3 4`.
In fact, this is so common that a function is provided to do exactly this: `⍳`, called "`iota`".

When invoked monadically, `⍳` accepts an argument indicating the size of the resulting array:

[source,kap]
----
    ⍳5
┏━━━━━━━━━┓
┃0 1 2 3 4┃
┗━━━━━━━━━┛
----

The `⍳` function will be used in a lot of examples below.

=== Accessing data in arrays

==== Reading single values

KAP uses the square brackets to read values from an array, so to read second value from a 1-dimensional array, one would use the following syntax:

[source,kap]
----
foo ← 10 11 12 13 14 15 16
bar ← foo[1]                      ⍝ bar now contains the value 11
----

All arrays are zero-indexed, meaning that the first element (the value 10) can be read using `foo[0]`, the second using `foo[1]`, etc.

==== Reading multiple values

The value inside square brackets (i.e. the index) does not need to be a single number.
One can specify an array as in index itself.
The result will be an array with the corresponding values for each index.
For example:

[source,kap]
----
    foo ← 10 11 12 13 14 15 16
    foo[4 5 0]
┏━━━━━━━━┓
┃14 15 10┃
┗━━━━━━━━┛
----

The result is a 3-element array containing the values 14, 15 and 10. These are the values in the original array at indexes 4, 5 and 0.

To read a sequence of values from an array, the `⍳` function can be used together with array lookup.
Thus, to read the first 6 elements from an array, the following can be used:

[source,kap]
----
    foo ← 10 11 12 13 14 15 16 17 18 19
    foo[⍳6]
┏━━━━━━━━━━━━━━━━━┓
┃10 11 12 13 14 15┃
┗━━━━━━━━━━━━━━━━━┛
----

Of course, KAP provides other ways to slice arrays (as would be expected from an array language) and these methods will be discussed later.

=== Array dimensionality

All arrays have a dimensionality, or "`rank`" as it is often referred to.
Arrays in most languages are 1-dimensional, meaning that values in the array are addressed using a single number.
When creating an array using the syntax described in the previous section, the result is a 1-dimensional array.

==== Creating multidimensional arrays

To create an array of different dimensionality, the function `⍴` is used.
When called dyadically, this function takes an array of numbers to the left that indicates the sizes of the resulting array's dimensions, and changes the dimensions of the array specified on the right to confirm to the requested dimensions.

That description was probably a bit confusing, so an example is in order:

[source,kap]
----
foo ← 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14
bar ← 3 5 ⍴ foo
----

After running the above, the variable `foo` will contain a 1-dimensional array, while `bar` contains a 2-dimensional version of the same data.
The operation performed by `⍴` is referred to as "`reshape`" because it changes the shape of the array while preserving content.

Content of `foo`:

//[dpic]
//----
//GRAPH1: [ n = 15
//
//line from (0,0) to (n,0)
//line from (0,1) to (n,1)
//for x = 0 to n do {
//  line from (x,0) to (x,1)
//}
//
//for x = 0 to n-1 do {
//  sprintf("%g", x) at (x+0.5, 0.5) ht 0.15
//}
//] wid 25 at (0, 3.5)
//----

[cols="^1,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1,^1",width=60]
|===
|0 |1 |2 |3 |4 |5 |6 |7 |8 |9 |10 |11 |12 |13 |14
|===

Content of `bar`:

//[dpic]
//----
//GRAPH2: [ cols = 5; rows = 3
//
//for y = 0 to rows do {
//  line from (0,y) to (cols,y)
//}
//
//for x = 0 to cols do {
//  line from (x,0) to (x,rows)
//}
//
//i = 0
//for y = rows-1 to 0 by -1 do {
//  for x = 0 to cols-1 do {
//    sprintf("%g", i) at (x+0.5, y+0.5) ht 0.15
//    i = i+1
//  }
//}
//] wid 25 at (0,0)
//----

[cols="^1,^1,^1,^1,^1",width=25]
|===
|0  |1  |2  |3  |4
|5  |6  |7  |8  |9
|10 |11 |12 |13 |14
|===

To read a value from a 2-dimensional array, one have to use two indices:

[source,kap]
----
value ← bar[1;2]
----

After the above have been run, the variable `value` contains `7`.
That is to say, it contains the value in the second row and third column.

Just like the 1-dimensional case, one can always specify an array instead of a single value when reading values from a multidimensional array.
An example:

[source,kap]
----
bar[1;0 2 3]
----

This will return the following 1-dimensional array:

[cols="^1,^1,^1",width=15]
|===
|5 |7 |8
|===

It is also possible to read all values along a given axis by omitting the index:

[source,kap]
----
bar[;4]
----

This returns the following:

[cols="^1,^1,^1",width=10]
|===
|0 |5 |10
|===

==== Finding the dimensionality of an array

In the previous section, it was explained how `⍴` is called dyadically to set the dimensions of an array.
When called monadically, the function returns the dimensionality of its argument.

[source,kap]
----
foo ← 3 5 ⍴ ⍳15
bar ← ⍴ foo
----

After this code has been run, the variable `bar` will contain the array `3 5`.

From this it can be seen that `⍴ X ⍴ Y` will always return `X`.
This is because ths expression is parsed as `⍴ (X ⍴ Y)`, which is equivalent to first reshaping Y with dimensions X, and then returning the dimensions of this array.

=== TODO

*Array operations?*

== Flow control

=== If statements

The if statement looks similar to that of C:

[source,kap]
----
if(a < b) {
    io:println "a is less than b"
} else {
    io:println "a is not less than b"
}
----

However, in KAP, the if statement is a value which is set to the result of the last form in the evaluated clause.
An example:

[source,kap]
----
foo ← if(a < b) {
    10
} else {
    20
}
----

After executing the above, the variable `foo` will have the value `10` if `a` was less than `b`.

=== While loops

KAP provides a while loop that is similar to that of C and many of its descendents.
A while loop terminates once its condition is false.
The following example prints the numbers 0 to 19:

[source,kap]
----
i ← 0
while(i < 20) {
    io:println i
    i ← i+1
}
----

=== Exceptions

*TODO: Explain try/catch*

= KAP Reference

== List of built-in KAP functions

=== Functions

[cols=3,options=header,cols="1a,4a,4a"]
|===
|Function
|Monadic
|Dyadic

|`+`
|Complex conjugate
|Addition

|`-`
|Negation
|Subtraction

|`×`
|Signum
|Multiplication

|`÷`
|Reciprocal
|Division

|`\|`
|Magnitude
|Modulo (note that the arguments are reversed, for `a\|b`, the result is `b` modulo `a`)

|`⌈`
|Ceiling (return the smallest integer greater than or equal to the argument)
|Maximum of the two arguments

|`⌊`
|Floor (return the largest integer smaller than or equal to the argument)
|Minimum of the two arguments
|===

=== Operators

[cols=2,options=header,cols="1a,4a"]
|===
|Name
|Description

|`/`
|Reduce along last axis

|`⌿`
|Reduce along first axis (this is equivalent to `FN/[0]`)
|===

== Flow control

=== If statements

If statement with a single clause. Returns `⍬` if the condition is false.

[source,kap]
----
if (a) {
    result
}
----

If statement with both then and else clauses:

[source,kap]
----
if (a) {
    resultIfTrue
} else {
    resultIfFalse
}
----

=== When statement

The `when` statement can be used to check for multiple conditions. This is preferred to a long list of if/else if/else statements.

[source,kap]
----
when {
    (conditionA) { resultIfA }
    (conditionB) { resultIfB }
    (1)          { elseResult }
}
----

=== While statement

Executes the body until the condition is false:

[source,kap]
----
while (a) {
    code
}
----

=== Unwinding

The `unwindProtect` statement is used to execute one code block after another one, regardless of whether the first one performed a non-local exit (such as by throwing an exception):

[source,kap]
----
unwindProtect { mainCode } { unwind }
----

=== Throwing an exception

Exceptions are thrown using `→`. Exception have a type, represented by a symbol and some associated data. The following example throws an exception of type `:foo` with data `"test"`:

[source,kap]
----
:foo → "test"
----

When called monadically, `→` will throw an execption of type `:error`.

=== Catching exception

TODO: Need to define a syntax extension to make exception catching nice
